// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ColorPattern: typeof import('./src/components/MapGenerator/ColorPattern.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTreeV2: typeof import('element-plus/es')['ElTreeV2']
    Map: typeof import('./src/components/MapGenerator/Map.vue')['default']
    MapGenerator: typeof import('./src/components/MapGenerator/MapGenerator.vue')['default']
  }
}

export { }
